#!/usr/bin/env bash

# example

#sed -i 's/PHP_VERSION=72/PHP_VERSION=71/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/WORKSPACE_INSTALL_XDEBUG=false/WORKSPACE_INSTALL_XDEBUG=true/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/WORKSPACE_INSTALL_NODE=false/WORKSPACE_INSTALL_NODE=true/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/WORKSPACE_INSTALL_YARN=false/WORKSPACE_INSTALL_YARN=true/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/WORKSPACE_INSTALL_PYTHON=false/WORKSPACE_INSTALL_PYTHON=true/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/WORKSPACE_INSTALL_IMAGE_OPTIMIZERS=false/WORKSPACE_INSTALL_IMAGE_OPTIMIZERS=true/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/PHP_FPM_INSTALL_XDEBUG=false/PHP_FPM_INSTALL_XDEBUG=true/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/PHP_FPM_INSTALL_IMAGE_OPTIMIZERS=false/PHP_FPM_INSTALL_IMAGE_OPTIMIZERS=true/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/NGINX_HOST_HTTP_PORT=80/NGINX_HOST_HTTP_PORT='${NGINX_HTTP_PORT}'/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/NGINX_HOST_HTTPS_PORT=443/NGINX_HOST_HTTPS_PORT='${NGINX_HTTPS_PORT}'/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/MYSQL_VERSION=latest/MYSQL_VERSION=5.5/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/MYSQL_DATABASE=default/MYSQL_DATABASE=practiceo/g' ${LARADOCK_DIRECTORY_PATH}.env
#sed -i 's/MYSQL_USER=default/MYSQL_USER=practiceo/g' ${LARADOCK_DIRECTORY_PATH}.env
